version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore Sharpsolutions.Edt\Sharpsolutions.Edt.sln
build:
  project: Sharpsolutions.Edt\Sharpsolutions.Edt.sln
  verbosity: normal
os: Visual Studio 2015 CTP 6
cache:
  - C:\Users\appveyor\AppData\Local\NuGet\Cache
test:
  categories:
    except:
    - Integration
