version: 1.0.{build}
image: Visual Studio 2015
branches:
  only:
  - master
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore Sharpsolutions.Edt\Sharpsolutions.Edt.sln
build:
  project: Sharpsolutions.Edt\Sharpsolutions.Edt.sln
  verbosity: normal
cache:
  - Sharpsolutions.Edt\packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset 
test:
  categories:
    except:
    - '"Integration Test"'
