namespace Sharpsolutions.Edt.Domain.Trade
{
    public class AgricultureBuilder : StarportBuilderBase {
        protected override void AddGoods(Starport starport) {
            starport.Add(GetCommodity("Pesticides"),  false, true);
            starport.Add(GetCommodity("Agricultural Medicines"),  false, true);
            starport.Add(GetCommodity("Hydrogen Fuel"),  false, true);
            starport.Add(GetCommodity("Explosives"),  false, false);
            starport.Add(GetCommodity("Mineral Oil"),  true, false);
            starport.Add(GetCommodity("Consumer Technology"),  false, true);
            starport.Add(GetCommodity("Clothing"),  false, true);
            starport.Add(GetCommodity("Domestic Appliances"),  false, true);
            starport.Add(GetCommodity("Basic Narcotics"),  false, false);
            starport.Add(GetCommodity("Beer"),  false, false);
            starport.Add(GetCommodity("Wine"),  false, false);
            starport.Add(GetCommodity("Liquor"),  true, false);
            starport.Add(GetCommodity("Tobacco"),  true, false);
            starport.Add(GetCommodity("Animal Meat"),  true, true);
            starport.Add(GetCommodity("Coffee"),  true, true);
            starport.Add(GetCommodity("Fish"),  true, true);
            starport.Add(GetCommodity("Fruit"),  true, true);
            starport.Add(GetCommodity("Grain"),  true, true);
            starport.Add(GetCommodity("Tea"),  true, true);
            starport.Add(GetCommodity("Synthetic Meat"),  false, false);
            starport.Add(GetCommodity("Food Cartridges"),  false, false);
            starport.Add(GetCommodity("Algae"),  true, false);
            starport.Add(GetCommodity("Polymers"),  false, false);
            starport.Add(GetCommodity("Semiconductors"),  false, false);
            starport.Add(GetCommodity("Superconductors"),  false, false);
            starport.Add(GetCommodity("Marine Supplies"),  false, true);
            starport.Add(GetCommodity("Crop Harvesters"),  false, true);
            starport.Add(GetCommodity("Mineral Extractors"),  false, false);
            starport.Add(GetCommodity("Heliostatic Furnaces"),  false, false);
            starport.Add(GetCommodity("Basic Medicines"),  false, true);
            starport.Add(GetCommodity("Progenitor Cells"),  false, true);
            starport.Add(GetCommodity("Combat Stabilisers"),  false, false);
            starport.Add(GetCommodity("Performance Enhancers"),  false, false);
            starport.Add(GetCommodity("Palladium"),  false, false);
            starport.Add(GetCommodity("Silver"),  false, false);
            starport.Add(GetCommodity("Gold"),  false, false);
            starport.Add(GetCommodity("Copper"),  false, false);
            starport.Add(GetCommodity("Alaminium"),  false, false);
            starport.Add(GetCommodity("Beryllium"),  false, false);
            starport.Add(GetCommodity("Indium"),  false, false);
            starport.Add(GetCommodity("Lithium"),  false, false);
            starport.Add(GetCommodity("Tantalum"),  false, false);
            starport.Add(GetCommodity("Titanium"),  false, false);
            starport.Add(GetCommodity("Uranium"),  false, false);
            starport.Add(GetCommodity("Gallium"),  false, false);
            starport.Add(GetCommodity("Lepidolite"),  false, false);
            starport.Add(GetCommodity("Cobalt"),  false, false);
            starport.Add(GetCommodity("Gallite"),  false, false);
            starport.Add(GetCommodity("Indite"),  false, false);
            starport.Add(GetCommodity("Uraninite"),  false, false);
            starport.Add(GetCommodity("Bertrandite"),  false, false);
            starport.Add(GetCommodity("Coltan"),  false, false);
            starport.Add(GetCommodity("Bauxite"),  false, false);
            starport.Add(GetCommodity("Rutile"),  false, false);
            starport.Add(GetCommodity("HE Suits"),  false, false);
            starport.Add(GetCommodity("Bio Reducing Lichen"),  false, false);
            starport.Add(GetCommodity("Advanced Catalysers"),  false, false);
            starport.Add(GetCommodity("Resonating Separators"),  false, false);
            starport.Add(GetCommodity("Animal Monitors"),  false, true);
            starport.Add(GetCommodity("Aquaponic Systems"),  false, true);
            starport.Add(GetCommodity("Terrain Enrichment Systems"),  false, true);
            starport.Add(GetCommodity("Auto Fabricators"),  false, false);
            starport.Add(GetCommodity("Robotics"),  false, false);
            starport.Add(GetCommodity("Computer Components"),  false, false);
            starport.Add(GetCommodity("Leather"),  true, false);
            starport.Add(GetCommodity("Natural Fabrics"),  true, false);
            starport.Add(GetCommodity("Synthetic Fabrics"),  false, false);
            starport.Add(GetCommodity("Biowaste"),  true, true);
            starport.Add(GetCommodity("Scrap"),  false, false);
            starport.Add(GetCommodity("Battle Weapons"),  false, false);
            starport.Add(GetCommodity("Personal Weapons"),  false, false);
            starport.Add(GetCommodity("Reactive Armour"),  false, false);
            starport.Add(GetCommodity("Non-Lethal Weapons"),  false, true);
        }
    }
}