namespace Sharpsolutions.Edt.Domain.Trade {
    public class RefineryBuilder : StarportBuilderBase {
        protected override void AddGoods(Starport starport) {
            starport.Add("Pesticides", "Chemicals", false, false);
            starport.Add("Agricultural Medicines", "Chemicals", false, false);
            starport.Add("Hydrogen Fuel", "Chemicals", true, true);
            starport.Add("Explosives", "Chemicals", true, false);
            starport.Add("Mineral Oil", "Chemicals", false, true);
            starport.Add("Consumer Technology", "Consumer Items", false, true);
            starport.Add("Clothing", "Consumer Items", false, true);
            starport.Add("Domestic Appliances", "Consumer Items", false, true);
            starport.Add("Basic Narcotics", "Drugs", false, false);
            starport.Add("Beer", "Drugs", false, false);
            starport.Add("Wine", "Drugs", false, false);
            starport.Add("Liquor", "Drugs", false, false);
            starport.Add("Tobacco", "Drugs", false, false);
            starport.Add("Animal Meat", "Foods", false, true);
            starport.Add("Coffee", "Foods", false, true);
            starport.Add("Fish", "Foods", false, true);
            starport.Add("Fruit", "Foods", false, true);
            starport.Add("Grain", "Foods", false, true);
            starport.Add("Tea", "Foods", false, true);
            starport.Add("Synthetic Meat", "Foods", false, true);
            starport.Add("Food Cartridges", "Foods", false, true);
            starport.Add("Algae", "Foods", false, false);
            starport.Add("Polymers", "Industrial Materials", true, false);
            starport.Add("Semiconductors", "Industrial Materials", true, false);
            starport.Add("Superconductors", "Industrial Materials", true, false);
            starport.Add("Marine Supplies", "Machinery", false, false);
            starport.Add("Crop Harvesters", "Machinery", false, false);
            starport.Add("Mineral Extractors", "Machinery", false, false);
            starport.Add("Heliostatic Furnaces", "Machinery", false, true);
            starport.Add("Basic Medicines", "Medicines", false, true);
            starport.Add("Progenitor Cells", "Medicines", false, true);
            starport.Add("Combat Stabilisers", "Medicines", false, false);
            starport.Add("Performance Enhancers", "Medicines", false, false);
            starport.Add("Palladium", "Metals", false, false);
            starport.Add("Silver", "Metals", false, false);
            starport.Add("Gold", "Metals", false, false);
            starport.Add("Copper", "Metals", true, false);
            starport.Add("Alaminium", "Metals", true, false);
            starport.Add("Beryllium", "Metals", true, false);
            starport.Add("Indium", "Metals", true, false);
            starport.Add("Lithium", "Metals", true, false);
            starport.Add("Tantalum", "Metals", true, false);
            starport.Add("Titanium", "Metals", true, false);
            starport.Add("Uranium", "Metals", true, false);
            starport.Add("Gallium", "Minerals", true, false);
            starport.Add("Lepidolite", "Minerals", true, false);
            starport.Add("Cobalt", "Minerals", true, false);
            starport.Add("Gallite", "Minerals", false, true);
            starport.Add("Indite", "Minerals", false, true);
            starport.Add("Uraninite", "Minerals", false, true);
            starport.Add("Bertrandite", "Minerals", false, true);
            starport.Add("Coltan", "Minerals", false, true);
            starport.Add("Bauxite", "Minerals", false, true);
            starport.Add("Rutile", "Minerals", false, true);
            starport.Add("HE Suits", "Technology", false, true);
            starport.Add("Bio Reducing Lichen", "Technology", false, false);
            starport.Add("Advanced Catalysers", "Technology", false, true);
            starport.Add("Resonating Separators", "Technology", false, true);
            starport.Add("Animal Monitors", "Technology", false, false);
            starport.Add("Aquaponic Systems", "Technology", false, false);
            starport.Add("Terrain Enrichment Systems", "Technology", false, false);
            starport.Add("Auto Fabricators", "Technology", false, false);
            starport.Add("Robotics", "Technology", false, false);
            starport.Add("Computer Components", "Technology", false, false);
            starport.Add("Leather", "Textiles", false, false);
            starport.Add("Natural Fabrics", "Textiles", false, false);
            starport.Add("Synthetic Fabrics", "Textiles", true, false);
            starport.Add("Biowaste", "Waste", true, false);
            starport.Add("Scrap", "Waste", false, true);
            starport.Add("Battle Weapons", "Weapons", false, false);
            starport.Add("Personal Weapons", "Weapons", false, false);
            starport.Add("Reactive Armour", "Weapons", false, false);
            starport.Add("Non-Lethal Weapons", "Weapons", false, true);

        }
    }
}