namespace Sharpsolutions.Edt.Domain.Trade {
    public class RefineryBuilder : StarportBuilderBase {
        protected override void AddGoods(Starport starport) {
            starport.Add(GetCommodity("Pesticides"), false, false);
            starport.Add(GetCommodity("Agricultural Medicines"), false, false);
            starport.Add(GetCommodity("Hydrogen Fuel"), true, true);
            starport.Add(GetCommodity("Explosives"), true, false);
            starport.Add(GetCommodity("Mineral Oil"), false, true);
            starport.Add(GetCommodity("Consumer Technology"), false, true);
            starport.Add(GetCommodity("Clothing"), false, true);
            starport.Add(GetCommodity("Domestic Appliances"), false, true);
            starport.Add(GetCommodity("Basic Narcotics"), false, false);
            starport.Add(GetCommodity("Beer"), false, false);
            starport.Add(GetCommodity("Wine"), false, false);
            starport.Add(GetCommodity("Liquor"), false, false);
            starport.Add(GetCommodity("Tobacco"), false, false);
            starport.Add(GetCommodity("Animal Meat"), false, true);
            starport.Add(GetCommodity("Coffee"), false, true);
            starport.Add(GetCommodity("Fish"), false, true);
            starport.Add(GetCommodity("Fruit"), false, true);
            starport.Add(GetCommodity("Grain"), false, true);
            starport.Add(GetCommodity("Tea"), false, true);
            starport.Add(GetCommodity("Synthetic Meat"), false, true);
            starport.Add(GetCommodity("Food Cartridges"), false, true);
            starport.Add(GetCommodity("Algae"), false, false);
            starport.Add(GetCommodity("Polymers"), true, false);
            starport.Add(GetCommodity("Semiconductors"), true, false);
            starport.Add(GetCommodity("Superconductors"), true, false);
            starport.Add(GetCommodity("Marine Supplies"), false, false);
            starport.Add(GetCommodity("Crop Harvesters"), false, false);
            starport.Add(GetCommodity("Mineral Extractors"), false, false);
            starport.Add(GetCommodity("Heliostatic Furnaces"), false, true);
            starport.Add(GetCommodity("Basic Medicines"), false, true);
            starport.Add(GetCommodity("Progenitor Cells"), false, true);
            starport.Add(GetCommodity("Combat Stabilisers"), false, false);
            starport.Add(GetCommodity("Performance Enhancers"), false, false);
            starport.Add(GetCommodity("Palladium"), false, false);
            starport.Add(GetCommodity("Silver"), false, false);
            starport.Add(GetCommodity("Gold"), false, false);
            starport.Add(GetCommodity("Copper"), true, false);
            starport.Add(GetCommodity("Alaminium"), true, false);
            starport.Add(GetCommodity("Beryllium"), true, false);
            starport.Add(GetCommodity("Indium"), true, false);
            starport.Add(GetCommodity("Lithium"), true, false);
            starport.Add(GetCommodity("Tantalum"), true, false);
            starport.Add(GetCommodity("Titanium"), true, false);
            starport.Add(GetCommodity("Uranium"), true, false);
            starport.Add(GetCommodity("Gallium"), true, false);
            starport.Add(GetCommodity("Lepidolite"), true, false);
            starport.Add(GetCommodity("Cobalt"), true, false);
            starport.Add(GetCommodity("Gallite"), false, true);
            starport.Add(GetCommodity("Indite"), false, true);
            starport.Add(GetCommodity("Uraninite"), false, true);
            starport.Add(GetCommodity("Bertrandite"), false, true);
            starport.Add(GetCommodity("Coltan"), false, true);
            starport.Add(GetCommodity("Bauxite"), false, true);
            starport.Add(GetCommodity("Rutile"), false, true);
            starport.Add(GetCommodity("HE Suits"), false, true);
            starport.Add(GetCommodity("Bio Reducing Lichen"), false, false);
            starport.Add(GetCommodity("Advanced Catalysers"), false, true);
            starport.Add(GetCommodity("Resonating Separators"), false, true);
            starport.Add(GetCommodity("Animal Monitors"), false, false);
            starport.Add(GetCommodity("Aquaponic Systems"), false, false);
            starport.Add(GetCommodity("Terrain Enrichment Systems"), false, false);
            starport.Add(GetCommodity("Auto Fabricators"), false, false);
            starport.Add(GetCommodity("Robotics"), false, false);
            starport.Add(GetCommodity("Computer Components"), false, false);
            starport.Add(GetCommodity("Leather"), false, false);
            starport.Add(GetCommodity("Natural Fabrics"), false, false);
            starport.Add(GetCommodity("Synthetic Fabrics"), true, false);
            starport.Add(GetCommodity("Biowaste"), true, false);
            starport.Add(GetCommodity("Scrap"), false, true);
            starport.Add(GetCommodity("Battle Weapons"), false, false);
            starport.Add(GetCommodity("Personal Weapons"), false, false);
            starport.Add(GetCommodity("Reactive Armour"), false, false);
            starport.Add(GetCommodity("Non-Lethal Weapons"), false, true);

        }
    }
}