// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Sharpsolutions.Edt.Data.Migrations
{
    
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class InsertDefaultCommodities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InsertDefaultCommodities));
        
        string IMigrationMetadata.Id
        {
            get { return "201412121958358_InsertDefaultCommodities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
