// <auto-generated />
using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Sharpsolutions.Edt.Data.Migrations
{
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddUniqueConstraintsOnStarPort : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddUniqueConstraintsOnStarPort));
        
        string IMigrationMetadata.Id
        {
            get { return "201502231520536_AddUniqueConstraintsOnStarPort"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
